# Generated by Django 5.0.1 on 2024-01-18 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameOfClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number_of_students', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('grandfather_name', models.CharField(max_length=255)),
                ('number_of_tazkira', models.PositiveIntegerField(blank=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student', to='office.nameofclass')),
            ],
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('attendence_status', models.CharField(choices=[('P', 'PRESENT'), ('A', 'ABSENT')], default='A', max_length=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='office.student')),
            ],
        ),
        migrations.CreateModel(
            name='ResultsOfOneYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maths', models.PositiveSmallIntegerField()),
                ('litriture', models.PositiveSmallIntegerField()),
                ('physics', models.PositiveSmallIntegerField()),
                ('geology', models.PositiveSmallIntegerField()),
                ('chemistry', models.PositiveIntegerField()),
                ('total_number', models.PositiveIntegerField()),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='office.nameofclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='office.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='office.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='nameofclass',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='name_of_class', to='office.teacher'),
        ),
    ]
