# Generated by Django 5.0.1 on 2024-01-24 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nameofclass',
            name='number_of_students',
        ),
    ]
