# Generated by Django 5.0.1 on 2024-02-20 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_alter_attendence_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultsofoneyear',
            name='teacher',
        ),
    ]
