# Generated by Django 5.0.1 on 2024-02-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_remove_resultsofoneyear_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultsofoneyear',
            name='percentage',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
