# Generated by Django 5.0.1 on 2024-02-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_alter_resultsofoneyear_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultsofoneyear',
            name='date_created',
            field=models.DateField(auto_now_add=True, default='2024-01-10'),
            preserve_default=False,
        ),
    ]
