# Generated by Django 5.0.1 on 2024-02-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0009_resultsofoneyear_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultsofoneyear',
            name='chemistry',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resultsofoneyear',
            name='geology',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resultsofoneyear',
            name='litriture',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resultsofoneyear',
            name='maths',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resultsofoneyear',
            name='physics',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resultsofoneyear',
            name='total_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
