# Generated by Django 5.0.1 on 2024-02-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0010_alter_resultsofoneyear_chemistry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultsofoneyear',
            name='edification',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
