# Generated by Django 5.0.1 on 2024-02-22 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0012_alter_resultsofoneyear_chemistry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultsofoneyear',
            name='percentage',
            field=models.FloatField(null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
